version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s %(levelname)s %(name)s %(filename)s %(lineno)d %(threadName)s : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
  uvicorn.error:
    level: INFO
    handlers: [console]
  uvicorn.access:
    level: INFO
    handlers: [console]
root:
  level: INFO
  handlers: [console]
